USE DATABASE CS5542_DB;

CREATE OR REPLACE TABLE RAW.DOCS(
  DOC_ID STRING,
  TITLE STRING,
  SOURCE STRING,
  TEXT STRING,
  CREATED_AT TIMESTAMP_NTZ
);
  
CREATE OR REPLACE TABLE APP.CHUNKS (
  CHUNK_ID STRING,
  DOC_ID STRING,
  PAGE_NUM INT, 
  CHUNK_TEXT STRING
)


CREATE OR REPLACE TABLE APP.MASTER_CLAUSE (
    FILENAME STRING,
    PARTIES STRING,
    AGREEMENT_DATE DATE,
    EFFECTIVE_DATE DATE,
    EXPIRATION_DATE DATE,
    RENEWAL_TERM STRING,
    NOTICE_PERIOD_TO_TERMINATE_RENEWAL STRING,
    GOVERNING_LAW STRING,
    COMPETITIVE_RESTRICTION STRING,
    NON_COMPETE STRING 
)
